drop table if exists reminders cascade;
drop table if exists guests cascade;
drop table if exists events cascade;
drop table if exists templates cascade;
drop table if exists users cascade;

create table events (
  id bigint generated by default as identity primary key,
  name text not null,
  date date not null,
  time text not null,
  venue text not null,
  description text not null default '',
  status text not null check (status in ('upcoming', 'ongoing', 'completed', 'cancelled')),
  color text not null
);

create table guests (
  id bigint generated by default as identity primary key,
  "firstName" text not null,
  "lastName" text not null,
  email text not null,
  phone text not null,
  "eventId" bigint not null references events(id) on delete cascade,
  rsvp text not null check (rsvp in ('pending', 'confirmed', 'declined'))
);

create table reminders (
  id bigint generated by default as identity primary key,
  "eventId" bigint not null references events(id) on delete cascade,
  type text not null check (type in ('email', 'sms', 'push')),
  "triggerBefore" text not null check ("triggerBefore" in ('15m', '1h', '3h', '24h', '48h', '1w')),
  message text not null default '',
  status text not null check (status in ('scheduled', 'sent', 'failed')),
  "createdAt" date not null
);

create table templates (
  id bigint generated by default as identity primary key,
  name text not null,
  bg text not null,
  "textColor" text not null
);

create table users (
  id bigint generated by default as identity primary key,
  "firstName" text not null,
  "lastName" text not null,
  email text not null unique,
  password text not null,
  role text not null,
  "createdAt" date not null
);

insert into events (id, name, date, time, venue, description, status, color) values
  (1, 'Annual Graduation Dinner', '2026-06-15', '18:00', 'Eko Hotel & Suites, Lagos', 'Faculty of Education annual graduation dinner ceremony', 'upcoming', '#1a1a2e'),
  (2, 'Tech Innovation Summit', '2026-07-20', '09:00', 'NOUN Study Centre, Victoria Island', 'Educational technology conference for professionals', 'upcoming', '#0d4f3c'),
  (3, 'Farewell Party - Dr. Okafor', '2026-04-10', '16:00', 'Radisson Blu Hotel, Lagos', 'Retirement celebration for Dr. Okafor', 'completed', '#9d4b6b');

insert into guests (id, "firstName", "lastName", email, phone, "eventId", rsvp) values
  (1, 'Amaka', 'Okonkwo', 'amaka.o@email.com', '+234 801 234 5678', 1, 'confirmed'),
  (2, 'Ibrahim', 'Musa', 'ibrahim.m@noun.edu.ng', '+234 802 345 6789', 1, 'confirmed'),
  (3, 'Blessing', 'Eze', 'blessing.e@gmail.com', '+234 803 456 7890', 2, 'pending'),
  (4, 'Taiwo', 'Babatunde', 'taiwo.b@email.com', '+234 806 789 0123', 3, 'confirmed');

insert into reminders (id, "eventId", type, "triggerBefore", message, status, "createdAt") values
  (1, 1, 'email', '24h', '', 'scheduled', '2026-05-01'),
  (2, 1, 'sms', '1h', 'Event starts soon!', 'scheduled', '2026-05-01'),
  (3, 3, 'email', '24h', '', 'sent', '2026-04-08');

insert into templates (id, name, bg, "textColor") values
  (1, 'Midnight Luxe', '#1a1a2e', '#f5a623'),
  (2, 'Blush Garden', '#f8e1e7', '#9d4b6b'),
  (3, 'Classic Ivory', '#fefaf0', '#5c4a1e'),
  (4, 'Deep Emerald', '#0d4f3c', '#a8e6cf'),
  (5, 'Royal Blue', '#1a237e', '#e3f2fd'),
  (6, 'Sunset Warm', '#e65c00', '#fff3cd');

insert into users (id, "firstName", "lastName", email, password, role, "createdAt") values
  (1, 'John', 'Adeyemi', 'john@eventcraft.com', 'password123', 'Event Coordinator', '2026-01-01');

select setval(pg_get_serial_sequence('events', 'id'), (select max(id) from events));
select setval(pg_get_serial_sequence('guests', 'id'), (select max(id) from guests));
select setval(pg_get_serial_sequence('reminders', 'id'), (select max(id) from reminders));
select setval(pg_get_serial_sequence('templates', 'id'), (select max(id) from templates));
select setval(pg_get_serial_sequence('users', 'id'), (select max(id) from users));
